name: build and test 
on:
  push:
    branches:
      - main
env:
  docker_image: suryaln/pradeep:${{ github.run_number }}
jobs:
  We-are-going-to-perform-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git Repo
        uses: actions/checkout@v7
      - name: Docker image build
        run: docker build -t $docker_image .
      - name: DockerHub Login
        uses: docker/login-action@v4
        with:
          username: ${{vars.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASS}}
      - name: Docker Image Push
        run: docker push ${{env.docker_image}}
  We-Are-Going-To-Deploy:
    needs: We-are-going-to-perform-ci
    runs-on: ubuntu-latest
    steps:
      - name: SSH Login
        uses: appleboy/ssh-action@v1
        with:
          host: ${{vars.machine_ip}}
          username: ubuntu 
          key: ${{secrets.machine_password}}
          port: 22
          script: |
            sudo -i
            apt update && apt install docker.io -y
            docker pull ${{env.docker_image}}
            docker run -itd --name action -p 80:80 ${{env.docker_image}}
            
          
 
    
