name: build and test 
on:
  push:
    branches:
      - main
jobs:
  We-are-going-to-perform-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git Repo
        uses: actions/checkout@v7
      - name: Docker image build
        run: docker build -t suryaln/pradeep:githubaction .
      - name: DockerHub Login
        uses: docker/login-action@v4
        with:
          username: ${{vars.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASS}}
      - name: Docker Image Push
        run: docker push suryaln/pradeep:githubaction
    
