name: build and test 
on:
  workflow_dispatch:  
jobs:
  We-are-going-to-perform-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git Repo
        uses: actions/checkout@v7
      - name: file iruka ??
        run: ls
      - name: install Node Dependencies
        run: npm install
      - name: build Node
        run: npm run build
        
    
